ALTER TABLE student ALTER COLUMN birthday SET NOT NULL;
ALTER TABLE mark ALTER COLUMN mark SET DATA TYPE INT, ADD CONSTRAINT mark_check CHECK (mark BETWEEN 1 AND 10),ALTER COLUMN student_id SET NOT NULL, ALTER COLUMN subject_id SET NULL;
ALTER TABLE subject ADD CONSTRAINT grade_range CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE paymenttype ADD CONSTRAINT unique_name UNIQUE (name);
ALTER TABLE payment ALTER COLUMN type_id SET NOT NULL, ALTER COLUMN amount SET NOT NULL, ALTER COLUMN payment_date SET NOT NULL;
