ALTER TABLE student ALTER COLUMN birthday SET NOT NULL;
ALTER TABLE mark ALTER COLUMN mark INT CHECK (mark BETWEEN 1 AND 10) NOT NULL, ALTER COLUMN student_id SET NOT NULL, ALTER COLUMN subject_id SET NOT NULL;
ALTER TABLE subject ALTER COLUMN grade INT CHECK (grade BETWEEN 1 AND 5);
ALTER TABLE paymenttype ADD CONSTRAINT unique_name UNIQUE (name);
ALTER TABLE Payment ALTER COLUMN type_id SET NOT NULL, ALTER COLUMN amount SET NOT NULL, ALTER COLUMN payment_date SET NOT NULL;
